
package com.baeldung.jaxws.server.topdown;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-07-28T09:36:16.372-04:00
 * Generated source version: 3.2.0
 * 
 */
public final class EmployeeServiceTopDown_EmployeeServiceTopDownSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://topdown.server.jaxws.baeldung.com/", "TestService");

    private EmployeeServiceTopDown_EmployeeServiceTopDownSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TestService ss = new TestService(wsdlURL, SERVICE_NAME);
        EmployeeServiceTopDown port = ss.getEmployeeServiceTopDownSOAP();  
        
        {
        System.out.println("Invoking countEmployees...");
        int _countEmployees__return = port.countEmployees();
        System.out.println("countEmployees.result=" + _countEmployees__return);


        }

        System.exit(0);
    }

}
