package com.baeldung.jaxws.server.topdown;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-07-28T09:36:16.395-04:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://topdown.server.jaxws.baeldung.com/", name = "EmployeeServiceTopDown")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmployeeServiceTopDown {

    @WebMethod(action = "http://topdown.server.jaxws.baeldung.com/               EmployeeServiceTopDown/countEmployees")
    @WebResult(name = "countEmployeesResponse", targetNamespace = "http://topdown.server.jaxws.baeldung.com/", partName = "parameters")
    public int countEmployees();
}
