package com.baeldung.jaxws.server.topdown;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-07-28T09:36:16.398-04:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "TestService", 
                  wsdlLocation = "classpath:wsdl/test_service.wsdl",
                  targetNamespace = "http://topdown.server.jaxws.baeldung.com/") 
public class TestService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://topdown.server.jaxws.baeldung.com/", "TestService");
    public final static QName EmployeeServiceTopDownSOAP = new QName("http://topdown.server.jaxws.baeldung.com/", "EmployeeServiceTopDownSOAP");
    static {
        URL url = TestService.class.getClassLoader().getResource("wsdl/test_service.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TestService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/test_service.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public TestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TestService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EmployeeServiceTopDown
     */
    @WebEndpoint(name = "EmployeeServiceTopDownSOAP")
    public EmployeeServiceTopDown getEmployeeServiceTopDownSOAP() {
        return super.getPort(EmployeeServiceTopDownSOAP, EmployeeServiceTopDown.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServiceTopDown
     */
    @WebEndpoint(name = "EmployeeServiceTopDownSOAP")
    public EmployeeServiceTopDown getEmployeeServiceTopDownSOAP(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceTopDownSOAP, EmployeeServiceTopDown.class, features);
    }

}
